"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar/NavBar";

import Providers from "../store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Artify",
  description: "Generated by Artify Corporation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>

          <body className={inter.className}>
            <NavBar />
            {children}
          </body>

      </Providers>
    </html>
  );
}
