import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar/NavBar";
import ProviderGoogle from "../components/ProviderGoogle";
import Providers from "../store/provider";
import { getAllCategories } from "../app/api/category/controllers";
import { getAllProvinces } from "../app/api/provinces/controllers";
import { getAllProducts } from "../app/api/products/controllers";
import Preloader from "../components/Preloader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Artify",
  description: "Generated by Artify Corporation",
};

const dataFetching = async () => {
  const categories = await getAllCategories();
  const provinces = await getAllProvinces();
  const products = await getAllProducts();
  return {
    categories,
    provinces,
    products,
  };
};

export default async function RootLayout({ children }) {
  const data = await dataFetching();
  return (
    <html lang="en">
      <Providers>
        <Preloader data={data} />
        <ProviderGoogle>
          <body className={inter.className}>
            <NavBar />
            {children}
          </body>
        </ProviderGoogle>
      </Providers>
    </html>
  );
}
