export const publicacionesArtesania = [
    {
      id: 1,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Artesanía de cerámica",
      precio: 50,
      username: "usuario1",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 2,
      imagenProducto: "https://i.pinimg.com/originals/2b/6c/88/2b6c88efb45d2ea946daf216c0a22b55.jpg",
      titulo: "Tejido a mano",
      precio: 30,
      username: "usuario2",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 3,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Joyas de plata",
      precio: 80,
      username: "usuario3",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 4,
      imagenProducto: "https://i.pinimg.com/originals/2b/6c/88/2b6c88efb45d2ea946daf216c0a22b55.jpg",
      titulo: "Escultura de madera",
      precio: 120,
      username: "usuario4",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 5,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Pintura al óleo",
      precio: 200,
      username: "usuario5",
      imagenUsuario: "https://i.pinimg.com/originals/2b/6c/88/2b6c88efb45d2ea946daf216c0a22b55.jpg",
    },
    {
      id: 6,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Tejido de macramé",
      precio: 45,
      username: "usuario6",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 7,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Cestería tradicional",
      precio: 60,
      username: "usuario7",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 8,
      imagenProducto: "https://i.pinimg.com/originals/2b/6c/88/2b6c88efb45d2ea946daf216c0a22b55.jpg",
      titulo: "Collares de piedras",
      precio: 25,
      username: "usuario8",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 9,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Cuadros en acuarela",
      precio: 150,
      username: "usuario9",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
    {
      id: 10,
      imagenProducto: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
      titulo: "Escultura en metal",
      precio: 180,
      username: "usuario10",
      imagenUsuario: "https://cdn.forbes.com.mx/2014/08/Cortesia-Artesanos-Mexico.jpg",
    },
  ];
  
  